# Status values
STATUS_ALL = "L"
STATUS_ACTIVE = "A"
STATUS_INACTIVE = "I"
STATUS_DELETED = "D"

DISP_NAME_STATUS_ACTIVE = "Active"
DISP_NAME_STATUS_INACTIVE = "Inactive"

#User status values for view purpose
USER_STATUS_RECENT = "R"
USER_STATUS_ALL = "A"
USER_STATUS_PENDING = "P"
USER_STATUS_COMPLETED = "C"

DISP_USER_ROLE_SUPER_ADMIN = "Super Admin"
DISP_USER_ROLE_DEPT_ADMIN = "Department Admin"
DISP_USER_ROLE_DEPT_USER = "Department User"
DISP_USER_ROLE_UNIT_ADMIN = "Unit Admin"
DISP_USER_ROLE_RESOURCE_MANAGER = "Resource Manager"
DISP_USER_ROLE_DATUK_SUK = "Datuk SUK"
DISP_USER_ROLE_SUK_DEPUTY = "SUK Deputy"
DISP_USER_ROLE_HUMAN_RESOURCE = "Human Resource"
DISP_USER_ROLE_CHIEF_MINISTER = "Y.A.B Chief Minister"